apiVersion: v1
kind: Pod
metadata:
  labels:
    run: postgres
  name: postgres
spec:
  volumes:
  - name: pg-data
    hostPath:
      path: /data/postgres
  containers:
  - image: postgres:10.4
    name: postgres
    ports:
    - containerPort: 5432
      name: postgres
    volumeMounts:
    - name: pg-data
      mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: postgres
  name: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 30222
    protocol: TCP
    targetPort: 5432
  selector:
    run: postgres
